# Generated by Django 4.0.1 on 2022-03-07 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ordermodel_sessionmodel_usermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_name',
        ),
    ]
