# Generated by Django 4.0.1 on 2022-03-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_first_name_usermodel_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='settingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playstation', models.IntegerField()),
                ('xbox', models.IntegerField()),
            ],
        ),
    ]
