# Generated by Django 4.0.1 on 2022-03-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_settingsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settingsmodel',
            old_name='playstation',
            new_name='playstation_auction',
        ),
        migrations.RenameField(
            model_name='settingsmodel',
            old_name='xbox',
            new_name='playstation_comfort',
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='xbox_auction',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='xbox_comfort',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
