# Generated by Django 4.0.1 on 2022-03-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_playstation_settingsmodel_playstation_auction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='cur',
            field=models.CharField(default='usd', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='message',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
