# Generated by Django 4.0.1 on 2022-03-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ordermodel_cur_ordermodel_message_ordermodel_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='review_mess',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='review_star',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
