# Generated by Django 4.0.1 on 2022-03-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ordermodel_review_mess_ordermodel_review_star_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('star', models.IntegerField(default=0)),
                ('mess', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
