# Generated by Django 4.0.1 on 2022-03-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_reviewmodel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='message',
            field=models.CharField(default='Will be delivered soon...', max_length=255),
        ),
    ]
