# Generated by Django 4.0.1 on 2022-03-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_ordermodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='playstation_auction',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='playstation_comfort',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='xbox_auction',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='xbox_comfort',
            field=models.FloatField(),
        ),
    ]
