# Generated by Django 4.0.1 on 2022-03-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_settingsmodel_playstation_auction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
