# Generated by Django 3.1 on 2022-04-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220410_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='console',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
