# Generated by Django 3.1 on 2022-04-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20220411_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='console',
        ),
    ]
