# Generated by Django 3.1 on 2022-04-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_ordermodel_console'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='console',
            field=models.CharField(default='', max_length=10),
        ),
    ]
