# Generated by Django 3.1 on 2022-04-27 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20220426_1500'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mailBoxModel',
            new_name='Promotion',
        ),
    ]
