# Generated by Django 3.1 on 2022-04-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20220427_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='ea_account',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
